spring.datasource.url=jdbc:mysql://localhost:3306/code_review_ai

spring.datasource.username=root

spring.datasource.password=Pooji@123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

openai.api.key=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